// <auto-generated />
using System;
using Carpinteria.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Carpinteria.Migrations
{
    [DbContext(typeof(CarpinteriaContext))]
    [Migration("20250529030019_ConfiguracionPKyFK")]
    partial class ConfiguracionPKyFK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Carpinteria.Modelo.Insumo", b =>
                {
                    b.Property<int>("InsumoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsumoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<string>("Proovedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("InsumoId");

                    b.ToTable("Insumos");

                    b.HasDiscriminator<string>("Tipo").HasValue("Insumo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Carpinteria.Modelo.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("FechaCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InsumoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InsumoId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("Carpinteria.Modelo.Accesorio", b =>
                {
                    b.HasBaseType("Carpinteria.Modelo.Insumo");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Accesorio");
                });

            modelBuilder.Entity("Carpinteria.Modelo.Perfil", b =>
                {
                    b.HasBaseType("Carpinteria.Modelo.Insumo");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Largo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<double>("PesoPorMetro")
                        .HasColumnType("float");

                    b.ToTable("Insumos", t =>
                        {
                            t.Property("Color")
                                .HasColumnName("Perfil_Color");
                        });

                    b.HasDiscriminator().HasValue("Perfil");
                });

            modelBuilder.Entity("Carpinteria.Modelo.Vidrio", b =>
                {
                    b.HasBaseType("Carpinteria.Modelo.Insumo");

                    b.Property<double>("Ancho")
                        .HasColumnType("float");

                    b.Property<string>("Espesor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Largo")
                        .HasColumnType("float");

                    b.Property<int>("TipoVidrio")
                        .HasColumnType("int");

                    b.ToTable("Insumos", t =>
                        {
                            t.Property("Largo")
                                .HasColumnName("Vidrio_Largo");
                        });

                    b.HasDiscriminator().HasValue("Vidrio");
                });

            modelBuilder.Entity("Carpinteria.Modelo.Stock", b =>
                {
                    b.HasOne("Carpinteria.Modelo.Insumo", "Insumo")
                        .WithMany()
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insumo");
                });
#pragma warning restore 612, 618
        }
    }
}
